services:
  drive:
    build: 
      context: ./django_drive_server
    env_file:
      - .env
    ports:
      - "8000:8000" # drive port 8080
    depends_on:
      db:
        condition: service_healthy
  
  checker:
    build: 
      context: ./node_user_check
    env_file:
      - .env
    ports:
      - "8001:8001" # drive port 8001
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck: # checks if operational, if not wait and retry
      test: ["CMD-SHELL", "pg_isready -U db_admin -d docker_db"]
      interval: 6s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"  # adminer port 8080

volumes:
  postgres_data: