services:
  drive:
    build: 
      context: ./drive_server
    ports:
      - "8000:8000" # drive port 8080
    environment:
      - DATABASE_NAME=docker_db
      - DATABASE_USER=db_admin
      - DATABASE_PASSWORD=db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: docker_db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck: # checks if operational, if not wait and retry
      test: ["CMD-SHELL", "pg_isready -U db_admin -d docker_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"  # adminer port 8080

volumes:
  postgres_data: